version: 2
updates:
  # Main package dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "elwizard33"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "elwizard33"
    commit-message:
      prefix: "deps(frontend)"
      prefix-development: "deps-dev(frontend)"
      
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "elwizard33"
    commit-message:
      prefix: "ci"
