name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'docusaurus.config.ts'
      - 'sidebars.ts'
      - 'src/**/*.ts'  # for API docs generation

  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build documentation
      run: |
        echo "Temporarily skipping docs build due to require.resolveWeak compatibility issue"
        echo "Creating placeholder for GitHub Pages"
        mkdir -p build
        cat > build/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
          <title>OAS-MCP Documentation</title>
          <meta charset="utf-8">
        </head>
        <body>
          <h1>OAS-MCP Documentation</h1>
          <p>Documentation is temporarily unavailable due to a build compatibility issue.</p>
          <p>Please visit the <a href="https://github.com/elwizard33/oas-mcp">GitHub repository</a> for documentation in the meantime.</p>
        </body>
        </html>
        EOF
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: gh-pages
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
