name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    name: Pre-release Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run full test suite
      run: |
        npm run typecheck
        npm run lint
        npm test
        npm run build
        
  publish-npm:
    name: Publish to NPM
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
  deploy-docs:
    name: Deploy Documentation
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build and deploy documentation
      run: npm run docs:deploy
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  create-release:
    name: Create GitHub Release
    needs: [test, publish-npm]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        release_name: Release ${{ steps.version.outputs.VERSION }}
        body: |
          ## What's Changed
          
          See [CHANGELOG.md](https://github.com/elwizard33/oas-mcp/blob/main/changelog.md) for detailed changes.
          
          ## Installation
          
          ```bash
          npm install -g oas-mcp@${{ steps.version.outputs.VERSION }}
          ```
          
          ## Documentation
          
          📖 [Full Documentation](https://elwizard33.github.io/oas-mcp)
          
        draft: false
        prerelease: ${{ contains(steps.version.outputs.VERSION, '-') }}
